package Data_View;

import Data_Model.Graph;
import Data_Model.ProblemSolver;
import java.awt.Component;
import java.io.File;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class MainView extends javax.swing.JFrame {
    private File FiletoOpen;
    private Graph G;
    private ProblemSolver B;
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Data_Panel = new javax.swing.JPanel();
        OpenFileButton = new javax.swing.JButton();
        FileAddressTextField = new javax.swing.JFormattedTextField();
        jSeparator2 = new javax.swing.JSeparator();
        GraphGenerator = new javax.swing.JButton();
        GraphSolver = new javax.swing.JButton();
        GraphViewer = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileOpenerMenu = new javax.swing.JMenu();
        OpenFileMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        GenerateMenu = new javax.swing.JMenuItem();
        SolveMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TSP Solver");

        Data_Panel.setBackground(new java.awt.Color(113, 113, 113));

        OpenFileButton.setText("Browse");
        OpenFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileButtonActionPerformed(evt);
            }
        });

        FileAddressTextField.setText("...");

        GraphGenerator.setText("Generate Graph");
        GraphGenerator.setEnabled(false);
        GraphGenerator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphGeneratorActionPerformed(evt);
            }
        });

        GraphSolver.setText("Solve Graph");
        GraphSolver.setEnabled(false);
        GraphSolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphSolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Data_PanelLayout = new javax.swing.GroupLayout(Data_Panel);
        Data_Panel.setLayout(Data_PanelLayout);
        Data_PanelLayout.setHorizontalGroup(
            Data_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Data_PanelLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(Data_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Data_PanelLayout.createSequentialGroup()
                        .addComponent(FileAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(OpenFileButton)
                        .addGap(27, 27, 27))
                    .addGroup(Data_PanelLayout.createSequentialGroup()
                        .addComponent(GraphGenerator)
                        .addGap(47, 47, 47)
                        .addComponent(GraphSolver)
                        .addGap(236, 236, 236))))
        );
        Data_PanelLayout.setVerticalGroup(
            Data_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Data_PanelLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Data_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FileAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpenFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Data_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GraphSolver)
                    .addComponent(GraphGenerator))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout GraphViewerLayout = new javax.swing.GroupLayout(GraphViewer);
        GraphViewer.setLayout(GraphViewerLayout);
        GraphViewerLayout.setHorizontalGroup(
            GraphViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        GraphViewerLayout.setVerticalGroup(
            GraphViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));

        FileOpenerMenu.setText("File");

        OpenFileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data_View/open-file-icon.png"))); // NOI18N
        OpenFileMenu.setText("Open File");
        OpenFileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileMenuActionPerformed(evt);
            }
        });
        FileOpenerMenu.add(OpenFileMenu);

        jMenuBar1.add(FileOpenerMenu);

        jMenu2.setText("Run");

        GenerateMenu.setText("Generate");
        GenerateMenu.setEnabled(false);
        GenerateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateMenuActionPerformed(evt);
            }
        });
        jMenu2.add(GenerateMenu);

        SolveMenu.setText("Solve");
        SolveMenu.setEnabled(false);
        SolveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolveMenuActionPerformed(evt);
            }
        });
        jMenu2.add(SolveMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Data_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(GraphViewer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Data_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GraphViewer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GraphSolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphSolverActionPerformed
        try {
            B = new ProblemSolver(G.GetGraphMatrix(), G.GetNNode());
            String message = B.SolveWithBnB();
            JOptionPane.showMessageDialog(new JFrame(), message, 
                "Solution of TSP", JOptionPane.INFORMATION_MESSAGE);
        } catch (IllegalArgumentException | NullPointerException e) {
            String message = "Graph Not Found!!";
            JOptionPane.showMessageDialog(new JFrame(), message, "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_GraphSolverActionPerformed

    private void GraphGeneratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphGeneratorActionPerformed
        try {
            G = new Graph();
            G.ReadGraphFromFile(FiletoOpen);
            String message = "";
            for (Double[] Row : G.GetGraphMatrix()) {
                for (Double Column : Row) {
                    if (Column.isInfinite()) {
                        DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.ENGLISH);
                        symbols.setInfinity("∞");
                        DecimalFormat decimalFormat = new DecimalFormat("#.#####", symbols);
                        message += decimalFormat.format(Column) + " ";
                    } else {
                        message += Math.round(Column) + " ";
                    }
                }
                message += "\n";
            }
            JOptionPane.showMessageDialog(new JFrame(), message, 
                "Graph Matrix to be Solved", JOptionPane.INFORMATION_MESSAGE);
            GraphSolver.setEnabled(true);
            SolveMenu.setEnabled(true);
            //GraphView GV = new GraphView();
            //GV.init(G.GetGraphMatrix());
            //GraphViewer.add(GV);
        } catch (NumberFormatException e) {
            String message = "Wrong File Input!!";
            JOptionPane.showMessageDialog(new JFrame(), message, "Error",
                JOptionPane.ERROR_MESSAGE);
            GenerateMenu.setEnabled(true);
            GraphGenerator.setEnabled(true);
        }
    }//GEN-LAST:event_GraphGeneratorActionPerformed

    private void OpenFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileButtonActionPerformed
        File SavedDirectory = new File("directory.in");
        JFileChooser GraphMatrixChooser = new JFileChooser();
        GraphMatrixChooser.setCurrentDirectory(SavedDirectory);
        int returnVal = GraphMatrixChooser.showOpenDialog((Component)evt.
            getSource());
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            FiletoOpen = GraphMatrixChooser.getSelectedFile();
            FileAddressTextField.setText(FiletoOpen.getAbsolutePath());
        }
        GenerateMenu.setEnabled(true);
        GraphGenerator.setEnabled(true);
    }//GEN-LAST:event_OpenFileButtonActionPerformed

    private void OpenFileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileMenuActionPerformed
        File SavedDirectory = new File("directory.in");
        JFileChooser GraphMatrixChooser = new JFileChooser();
        GraphMatrixChooser.setCurrentDirectory(SavedDirectory);
        int returnVal = GraphMatrixChooser.showOpenDialog((Component)evt.
            getSource());
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            FiletoOpen = GraphMatrixChooser.getSelectedFile();
            FileAddressTextField.setText(FiletoOpen.getAbsolutePath());
        }
        GenerateMenu.setEnabled(true);
        GraphGenerator.setEnabled(true);
    }//GEN-LAST:event_OpenFileMenuActionPerformed

    private void GenerateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateMenuActionPerformed
        try {
            G = new Graph();
            G.ReadGraphFromFile(FiletoOpen);
            String message = "";
            for (Double[] Row : G.GetGraphMatrix()) {
                for (Double Column : Row) {
                    if (Column.isInfinite()) {
                        DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.ENGLISH);
                        symbols.setInfinity("∞");
                        DecimalFormat decimalFormat = new DecimalFormat("#.#####", symbols);
                        message += decimalFormat.format(Column) + " ";
                    } else {
                        message += Math.round(Column) + " ";
                    }
                }
                message += "\n";
            }
            JOptionPane.showMessageDialog(new JFrame(), message, 
                "Graph Matrix to be Solved", JOptionPane.INFORMATION_MESSAGE);
            GraphSolver.setEnabled(true);
            SolveMenu.setEnabled(true);
            GraphView GV = new GraphView();
            GV.init(G.GetGraphMatrix());
            GraphViewer.add(GV);
        } catch (NumberFormatException e) {
            String message = "Wrong File Input!!";
            JOptionPane.showMessageDialog(new JFrame(), message, "Error",
                JOptionPane.ERROR_MESSAGE);
            GenerateMenu.setEnabled(false);
            GraphGenerator.setEnabled(false);        
        }
    }//GEN-LAST:event_GenerateMenuActionPerformed

    private void SolveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolveMenuActionPerformed
        try {
            B = new ProblemSolver(G.GetGraphMatrix(), G.GetNNode());
            String message = B.SolveWithBnB();
            JOptionPane.showMessageDialog(new JFrame(), message, 
                "Solution of TSP", JOptionPane.INFORMATION_MESSAGE);
        } catch (IllegalArgumentException | NullPointerException e) {
            String message = "Graph Not Found!!";
            JOptionPane.showMessageDialog(new JFrame(), message, "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SolveMenuActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Data_Panel;
    private javax.swing.JFormattedTextField FileAddressTextField;
    private javax.swing.JMenu FileOpenerMenu;
    private javax.swing.JMenuItem GenerateMenu;
    private javax.swing.JButton GraphGenerator;
    private javax.swing.JButton GraphSolver;
    private javax.swing.JPanel GraphViewer;
    private javax.swing.JButton OpenFileButton;
    private javax.swing.JMenuItem OpenFileMenu;
    private javax.swing.JMenuItem SolveMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
